# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Build at 00:00 on every 15th day-of-month.
#   schedule:
#     - cron: "0 0 */15 * *"
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths-ignore: [ '**/README.md' ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ '**/README.md' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "idm"
  idm:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Set IDM_VER
      - name: Run version script
        run: echo "IDM_VER=$(wget "https://www.internetdownloadmanager.com/download.html" -qO- 2>&1 | grep -Po '=id.*[0-9]' | sed -r 's|=idman||;s|build||;s/./&./1;s/./&./4;s/./&./10')" >> $GITHUB_ENV

      # Runs a set of commands using the runners shell
      - name: Run a single-line script
        run: |
          sudo apt update && sudo apt install libfuse2 -y
          xvfb-run --server-args="-screen 0 1024x768x24" bash deploy.sh stable

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: idm-continuous-x86_64.AppImage
          path: 'dist'

  idm-wp:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Set IDM_VER
      - name: Run version script
        run: echo "IDM_VER=$(wget "https://www.internetdownloadmanager.com/download.html" -qO- 2>&1 | grep -Po '=id.*[0-9]' | sed -r 's|=idman||;s|build||;s/./&./1;s/./&./4;s/./&./10')_WP" >> $GITHUB_ENV

      # Runs a set of commands using the runners shell
      - name: Run a single-line script
        run: |
          sudo apt update && sudo apt install libfuse2 -y
          xvfb-run --server-args="-screen 0 1024x768x24" bash deploy.sh stablewp

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: idm-continuous-wp-x86_64.AppImage
          path: 'dist'

  release-stable:
    needs: [idm]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v1
        with:
          name: idm-continuous-x86_64.AppImage

      - name: release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: idm stable
          automatic_release_tag: stable
          prerelease: false
          draft: false
          files: |
            idm-continuous-x86_64.AppImage
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  release-stable-wp:
    needs: [idm-wp]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v1
        with:
          name: idm-continuous-wp-x86_64.AppImage

      - name: release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: idm stable with wineprefix
          automatic_release_tag: stable-wp
          prerelease: false
          draft: false
          files: |
            idm-continuous-wp-x86_64.AppImage
          repo_token: ${{ secrets.GITHUB_TOKEN }}
